"""tenants + byo-ai config + tenant links

Revision ID: 0a0d1fc304c5
Revises: 334169a5735a
Create Date: 2026-06-17 04:07:24.318954
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0a0d1fc304c5'
down_revision: Union[str, None] = '334169a5735a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('lti_registration_id', sa.Integer(), nullable=True),
    sa.Column('ai_provider', sa.String(length=32), nullable=True),
    sa.Column('ai_model', sa.String(length=128), nullable=True),
    sa.Column('ai_endpoint', sa.String(length=512), nullable=True),
    sa.Column('ai_deployment', sa.String(length=128), nullable=True),
    sa.Column('ai_api_key_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('external_ai_allowed', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('pii_minimization', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lti_registration_id'], ['lti_registrations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_slug'), ['slug'], unique=True)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_courses_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_courses_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_users_tenant_id', 'tenants', ['tenant_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('fk_users_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_courses_tenant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_courses_tenant_id'))
        batch_op.drop_column('tenant_id')

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_slug'))

    op.drop_table('tenants')
    # ### end Alembic commands ###
