"""materials, rubric detail, grounding

Revision ID: 1cad808c861d
Revises: 97677892a09c
Create Date: 2026-06-01 03:16:00.024982
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1cad808c861d'
down_revision: Union[str, None] = '97677892a09c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rubric_criteria', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('time_on_task_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('submitted_late', sa.Boolean(), nullable=True))

    with op.batch_alter_table('remediation_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grounded_on', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_modules', schema=None) as batch_op:
        batch_op.drop_column('grounded_on')

    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_column('submitted_late')
        batch_op.drop_column('time_on_task_minutes')
        batch_op.drop_column('attempts')
        batch_op.drop_column('rubric_criteria')

    op.drop_table('course_materials')
    # ### end Alembic commands ###
