"""user is_platform_admin flag

Revision ID: 4f91f26cce22
Revises: f0232f8b7f87
Create Date: 2026-06-17 15:57:35.023140
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4f91f26cce22'
down_revision: Union[str, None] = 'f0232f8b7f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_platform_admin', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_platform_admin')

    # ### end Alembic commands ###
