"""lti 1.3 registrations deployments nonces keys

Revision ID: 5ce2c05f82e5
Revises: 8df222faf2b2
Create Date: 2026-06-17 02:14:39.253776
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ce2c05f82e5'
down_revision: Union[str, None] = '8df222faf2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lti_registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=512), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('auth_login_url', sa.String(length=512), nullable=False),
    sa.Column('auth_token_url', sa.String(length=512), nullable=False),
    sa.Column('key_set_url', sa.String(length=512), nullable=False),
    sa.Column('audience', sa.String(length=512), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer', 'client_id', name='uq_lti_reg_iss_client')
    )
    with op.batch_alter_table('lti_registrations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lti_registrations_issuer'), ['issuer'], unique=False)

    op.create_table('lti_tool_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kid', sa.String(length=64), nullable=False),
    sa.Column('private_pem', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lti_tool_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lti_tool_keys_kid'), ['kid'], unique=True)

    op.create_table('lti_deployments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['lti_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_id', 'deployment_id', name='uq_lti_deployment')
    )
    op.create_table('lti_nonces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('nonce', sa.String(length=128), nullable=False),
    sa.Column('registration_id', sa.Integer(), nullable=True),
    sa.Column('target_link_uri', sa.String(length=1024), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['registration_id'], ['lti_registrations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lti_nonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lti_nonces_nonce'), ['nonce'], unique=False)
        batch_op.create_index(batch_op.f('ix_lti_nonces_state'), ['state'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lti_nonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lti_nonces_state'))
        batch_op.drop_index(batch_op.f('ix_lti_nonces_nonce'))

    op.drop_table('lti_nonces')
    op.drop_table('lti_deployments')
    with op.batch_alter_table('lti_tool_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lti_tool_keys_kid'))

    op.drop_table('lti_tool_keys')
    with op.batch_alter_table('lti_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lti_registrations_issuer'))

    op.drop_table('lti_registrations')
    # ### end Alembic commands ###
