"""assessment adaptive_enabled toggle

Revision ID: dddc2dee9312
Revises: 1cad808c861d
Create Date: 2026-06-01 03:55:23.837893
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dddc2dee9312'
down_revision: Union[str, None] = '1cad808c861d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'adaptive_enabled', sa.Boolean(), nullable=False, server_default=sa.true()
        ))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessments', schema=None) as batch_op:
        batch_op.drop_column('adaptive_enabled')

    # ### end Alembic commands ###
