"""lti auto_register_deployments flag

Revision ID: f0232f8b7f87
Revises: 0a0d1fc304c5
Create Date: 2026-06-17 05:18:22.330830
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f0232f8b7f87'
down_revision: Union[str, None] = '0a0d1fc304c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lti_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'auto_register_deployments', sa.Boolean(),
            server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lti_registrations', schema=None) as batch_op:
        batch_op.drop_column('auto_register_deployments')

    # ### end Alembic commands ###
